apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xoto-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://192.168.1.6:18080'
    targetRevision: 1.0.0
    chart: xoto-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: xoto-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
